### ISSUE TITLE
License for project?

### ISSUE THREAD

**Issue by zakrywilson** [huytd/vscode-nord-light#4]
I was wondering if there was a reason why there was no license for this project, like you have for [Tokyo City](https://github.com/huytd/vscode-tokyo-city/blob/master/LICENSE). Could this project have an MIT license, too? Thanks!

**Comment by huytd** [comment]
Yeah mostly because I forgot to create one 😅 I just added it. Thank you so much!

**Comment by zakrywilson** [comment]
Thank *you* – these themes are great 🙂
